### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by Default-01** [Danktuary/discord-message-components#10]
I am wondering how i can setup discord-message-components, im trying to set it up on VuePress v2. 

This is my project: https://github.com/Default-01/SlickBot-Docs

If anyone knows a guide I can use I would really appreciate it, if its not much work maybe someone can make a PR ?

Thanks in advance :)

**Comment by Danktuary** [comment]
Hi, you can refer to the [`@discord-message-components/vue/README.md`](https://github.com/Danktuary/discord-message-components/blob/main/packages/vue/README.md) page for basic setup instructions. You can also refer to [`discordjs/guide`'s `clientEnhanceApp.ts` file](https://github.com/discordjs/guide/blob/main/guide/.vuepress/clientAppEnhance.ts) as an example of a repo that uses this package with VuePress v2.

**Comment by Default-01** [comment]
But the discord.js guide uses Typescript, but i am using javascript. is there an example for that ?

**Comment by Default-01** [comment]
How can i register components globally ?
